# Copyright IBM Corp. 2023
# Made available under the MIT License

name: "Install StepZen CLI"
author: "IBM"
description: |
  Install the StepZen CLI. Assumes Node is already installed.

inputs:
  version:
    description: "StepZen CLI Version (defaults to latest)"
    required: true
    default: latest

runs:
  using: "composite"
  steps:
    - name: setup
      shell: bash
      run: |
        echo "WS" ${HOME}
        mkdir -p ${HOME}/.stepzen-cli
        cd ${HOME}/.stepzen-cli
    
    - id: install-stepzen-cli
      # retry due to occasional npm failure
      uses: nick-fields/retry@v3
      with:
        timeout_seconds: 120
        max_attempts: 3
        retry_wait_seconds: 2
        shell: bash
        command: npm install stepzen@${{ inputs.version }}  --verbose
    - run: stepzen version
      shell: bash
    - name: check
      shell: bash
      run: |
        ls ${HOME}/.stepzen-cli
